# Site settings
title: Andrew Shifflett
email: shifflett@andrewshifflett.com
description: "Personal website of Andrew Shifflett."
url: "http://andrewshifflett.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty
